### ISSUE TITLE
But Wait! time is incorrect

### ISSUE THREAD

**Issue by theonlyalterego** [tamadra/rank-up#5]
Timezone is being correctly detected, however the dialogue "But Wait at XX:XX pm, you'll have ## stamina to run:" is incorrect, or using the wrong timezone.

Timezone is found correctly as GMT -4.

Screenshot is taken at 8:03 PM EST (GMT -4). dialogue suggests waiting till 7:00 pm, which is in the past.

![2014-06-11 20_03_05-](https://cloud.githubusercontent.com/assets/1557814/3252633/150de826-f1c5-11e3-9233-b73fd2f65450.png)

**Comment by tamadra** [comment]
Thanks for the report. I'll take a look.

**Comment by tamadra** [comment]
Fixed and pushed. Thanks for the bug report.
