### ISSUE TITLE
if you enable starlight sanctuary dungeons, the magic search borks hard. [BUG]

### ISSUE THREAD

**Issue by bloodwars** [tamadra/rank-up#8]
multiple issues:
first enable all dungeons, then try these things:
-search for 17 stamina.  first option is queen of the gods + dual weapons for 9k, when KoG is ~14k
 it appears further down though, but it should start at #1
-search for 34 stam.  should be KoG/KoG, but it's not, it's dual weapons/QoG/KoG.  KoG/KoG is NOT even on the list... anywhere.
--search for 170, 340, etc.  it always picks DW/QoG and then a bunch of KoGs

345 or 350 would get you Dragons in the tower or lava tubes and then lots of KoG, but something's pretty wrong here.

**Comment by tamadra** [comment]
Thanks for reporting this, and for the detailed steps. However, I am unable to reproduce the same thing you're seeing; I attached screenshots of the results I'm seeing for 17 and 34 stamina.

Are you still seeing the same results? If so, could you attach screenshots to help me debug? Thanks.

![17 Stamina](https://cloud.githubusercontent.com/assets/7299481/5339617/7cd1b014-7e97-11e4-983b-37fbdf25d023.png)

![34 Stamina](https://cloud.githubusercontent.com/assets/7299481/5339616/7ccf6138-7e97-11e4-938d-44acb0237cac.png)

**Comment by bloodwars** [comment]
i'm getting expected results now... maybe it was an issue because the 1/2 stam effect was up.  i'll try it again next saturday when it's up again.  i should have taken screenshots.

**Comment by tamadra** [comment]
Ah, of course that makes sense. I can reproduce it when I set my computer time to the weekends (1/2 stamina for starlight sanctuary).

I'll fix it and push an update. Thanks.

**Comment by bloodwars** [comment]
well, 1/2 stam for tower of trials/giants, but yeah, glad you could repro. thanks!

**Comment by tamadra** [comment]
Yup, I mispoke. Half-stamina for Starlight would be awesome though, haha.

OK found the bug and fixed. Thanks.
